# https://taskfile.dev

version: '3'

vars:
  PROFILE: workshop-mb
  REQ_MINIKUBE_VERSION: "1.35.0"
  KPS_VERSION: "79.1.0"
  WELCOME: >
    Welcome! Thank you for showing your interest to this workshop.
    In order to run the playground, you need to have minikube and helm installed.
  FAREWELL: >
    Thank you for your time with us! We hope you found some useful tricks and tips for your tasks

includes:
  core:
    taskfile: ./k8s/taskfile.yml

tasks:
  default:
    cmds:
      - task: cluster.start
      - task: dns.add
      - task: core:deploy

  cluster.start:
    desc: Spin up a local cluster
    vars:
      CUR_MINIKUBE_VERSION: "$(minikube version --short | sed -e ''s/[v.]//g'')"
      MIN_MINIKUBE_VERSION: "$(echo {{.REQ_MINIKUBE_VERSION}} | sed -e ''s/[v.]//g'')"
    preconditions:
      - test -x "$(command -v docker)" 
      - test -x "$(command -v helm)"
      - test -x "$(command -v minikube)"
      - sh: '[ "{{.CUR_MINIKUBE_VERSION}}" -ge "{{.MIN_MINIKUBE_VERSION}}" ]'
        msg: |
          Minikube version is too old.
          Please upgrade to version {{.REQ_MINIKUBE_VERSION}} or higher.

    cmds:
      - echo '{{.WELCOME}}' 
      - minikube start --profile={{.PROFILE}} --cpus={{.CPU_COUNT | default "2"}} --memory='{{.MEMORY_SIZE | default "4g"}}'
      - |
        minikube addons -p {{.PROFILE}} enable headlamp 
        minikube addons -p {{.PROFILE}} enable metrics-server 
        minikube addons -p {{.PROFILE}} enable registry 
        minikube addons -p {{.PROFILE}} enable ingress
        minikube addons -p {{.PROFILE}} enable ingress-dns 
        minikube addons -p {{.PROFILE}} enable default-storageclass
        minikube addons -p {{.PROFILE}} enable kubetail
      - kubectl create token headlamp --duration 24h -n headlamp

  cluster.tunnel:
    desc: Run minikube tunnel (requires sudo; blocks until interrupted)
    cmds:
      - sudo minikube tunnel -p {{.PROFILE}}

  cluster.stop:
    desc: Stop the local cluster
    preconditions:
      - test -x "$(command -v docker)" 
      - test -x "$(command -v helm)"
      - test -x "$(command -v minikube)"
    
    cmds:
      - minikube stop --profile={{.PROFILE}}
      - minikube delete --profile={{.PROFILE}}
      - echo '{{.FAREWELL}}'

  dns.add:
    desc: "Configure local DNS to resolve cluster hostnames. Sudo access is required."
    cmds:
      - |
        DNS_IP=$(minikube ip -p {{.PROFILE}})
        if [ -z "$DNS_IP" ]; then
          echo "Could not get minikube IP for profile '{{.PROFILE}}'. Is the cluster running?"
          exit 1
        fi
        echo "Minikube IP found: $DNS_IP"
        
        sudo sed -i.back '/^# >>> minikube-workshop-mb$/,/^# <<< minikube-workshop-mb$/d' /etc/hosts;
        sudo tee -a /etc/hosts >/dev/null << EOF
        # >>> minikube-workshop-mb
        $DNS_IP  headlamp.test
        $DNS_IP  grafana.test
        $DNS_IP  alertmanager.test
        $DNS_IP  prometheus.test
        $DNS_IP  kubetail.test
        # <<< minikube-workshop-mb
        EOF

        echo "Configuration complete. You should now be able to resolve services like http://headlamp.test"

  dns.remove:
    desc: "Remove /etc/hosts entries for workshop ingress block"
    cmds:
      - |
        sudo sed -i.back -e '/^# >>> minikube-workshop-mb$/,/^# <<< minikube-workshop-mb$/d' /etc/hosts
        echo "/etc/hosts entries removed." 
