# https://taskfile.dev

version: '3'

vars:
  PROFILE: workshop-mb
  REQ_MINIKUBE_VERSION: "1.35.0"
  KPS_VERSION: "79.1.0"
  WELCOME: >
    Welcome! Thank you for showing your interest to this workshop.
    In order to run the playground, you need to have minikube and helm installed.
  FAREWELL: >
    Thank you for your time with us! We hope you found some useful tricks and tips for your tasks

tasks:
  default:
    cmds:
      - task: cluster.start
      - task: deploy.core-ingress-rules
      - task: configure.ingress-dns

  cluster.start:
    desc: Spin up a local cluster
    vars:
      CUR_MINIKUBE_VERSION: "$(minikube version --short | sed -e ''s/[v.]//g'')"
      MIN_MINIKUBE_VERSION: "$(echo {{.REQ_MINIKUBE_VERSION}} | sed -e ''s/[v.]//g'')"
    preconditions:
      - test -x "$(command -v docker)" 
      - test -x "$(command -v helm)"
      - test -x "$(command -v minikube)"
      - sh: '[ "{{.CUR_MINIKUBE_VERSION}}" -ge "{{.MIN_MINIKUBE_VERSION}}" ]'
        msg: |
          Minikube version is too old.
          Please upgrade to version {{.REQ_MINIKUBE_VERSION}} or higher.

    cmds:
      - echo '{{.WELCOME}}' 
      - minikube start --profile={{.PROFILE}} --cpus={{.CPU_COUNT | default "2"}} --memory='{{.MEMORY_SIZE | default "4g"}}'
      - |
        minikube addons -p {{.PROFILE}} enable headlamp 
        minikube addons -p {{.PROFILE}} enable metrics-server 
        minikube addons -p {{.PROFILE}} enable registry 
        minikube addons -p {{.PROFILE}} enable ingress
        minikube addons -p {{.PROFILE}} enable ingress-dns 
        minikube addons -p {{.PROFILE}} enable default-storageclass
        minikube addons -p {{.PROFILE}} enable kubetail
      - kubectl create token headlamp --duration 24h -n headlamp

  configure.ingress-dns:
    desc: "Configure local DNS to resolve cluster hostnames. Sudo access is required."
    cmds:
      - |
        DNS_IP=$(minikube ip -p {{.PROFILE}})
        if [ -z "$DNS_IP" ]; then
          echo "Could not get minikube IP for profile '{{.PROFILE}}'. Is the cluster running?"
          exit 1
        fi
        echo "Minikube IP found: $DNS_IP"
        
        OS=$(uname -s)
        if [ "$OS" = "Darwin" ]; then
          echo "Detected macOS. Creating resolver file for .test domain..."
          sudo mkdir -p /etc/resolver
          # The EOF marker for a here-document must not be indented.
          sudo tee /etc/resolver/minikube.test > /dev/null << EOF
          domain test
          nameserver $DNS_IP
          search_order 1
          timeout 5
        EOF
        elif [ "$OS" = "Linux" ]; then
          echo "Detected Linux. Configuring systemd-resolved for .test domain..."
          sudo mkdir -p /etc/systemd/resolved.conf.d
          # The EOF marker for a here-document must not be indented.
          sudo tee /etc/systemd/resolved.conf.d/minikube-test-domain.conf > /dev/null << EOF
          [Resolve]
          DNS=$DNS_IP
          Domains=~test
        EOF
          sudo systemctl restart systemd-resolved
          echo "systemd-resolved has been configured and restarted."
        else
          echo "Unsupported OS: $OS. Please configure DNS for *.test manually to point to $DNS_IP."
          exit 1
        fi

        echo "Configuration complete. You should now be able to resolve services like http://my-service.test"

  cluster.tunnel:
    desc: Run minikube tunnel (requires sudo; blocks until interrupted)
    cmds:
      - sudo minikube tunnel -p {{.PROFILE}}

  cluster.stop:
    desc: Stop the local cluster
    preconditions:
      - test -x "$(command -v docker)" 
      - test -x "$(command -v helm)"
      - test -x "$(command -v minikube)"
    
    cmds:
      - minikube stop --profile={{.PROFILE}}
      - minikube delete --profile={{.PROFILE}}
      - echo '{{.FAREWELL}}'

  deploy.core-ingress-rules:
    desc: "Deploy Ingress for basic services to make it accessible via dns names"
    cmds:
      - kubectl apply -f k8s/headlamp-ingress.yml

  get.headlamp-token:
    desc: Issue an access token for headlamp admin panel 
    cmds:
      - kubectl create token headlamp --duration 24h -n headlamp

  deploy.monitoring:
    desc: "Install/upgrade kube-prometheus-stack via Helm (official)"
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update
      - helm upgrade --install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --values k8s/monitoring/values.yaml --version {{.KPS_VERSION}}

  delete.monitoring:
    desc: "Uninstall kube-prometheus-stack via Helm"
    cmds:
      - helm uninstall monitoring -n monitoring
      - kubectl delete crd alertmanagerconfigs.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd alertmanagers.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd podmonitors.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd probes.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd prometheusagents.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd prometheuses.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd prometheusrules.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd scrapeconfigs.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd servicemonitors.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete crd thanosrulers.monitoring.coreos.com --ignore-not-found=true
      - kubectl delete ns monitoring --ignore-not-found=true

  hosts.add-ingress:
    desc: "Add /etc/hosts entries for ingress: headlamp.test, grafana.test, alertmanager.test, prometheus.test"
    cmds:
      - |
        OS=$(uname -s);
        if [ "$OS" = "Darwin" ]; then SED_INPLACE="sed -i ''"; else SED_INPLACE="sed -i"; fi;
        sudo sh -c "$SED_INPLACE -e '/^# >>> minikube-workshop-mb$/,/^# <<< minikube-workshop-mb$/d' /etc/hosts";
        sudo tee -a /etc/hosts >/dev/null << 'EOF'
        # >>> minikube-workshop-mb
        127.0.0.1  headlamp.test
        127.0.0.1  grafana.test
        127.0.0.1  alertmanager.test
        127.0.0.1  prometheus.test
        # <<< minikube-workshop-mb
        EOF

  hosts.remove-ingress:
    desc: "Remove /etc/hosts entries for workshop ingress block"
    cmds:
      - |
        OS=$(uname -s);
        if [ "$OS" = "Darwin" ]; then SED_INPLACE="sed -i ''"; else SED_INPLACE="sed -i"; fi;
        sudo sh -c "$SED_INPLACE -e '/^# >>> minikube-workshop-mb$/,/^# <<< minikube-workshop-mb$/d' /etc/hosts"


  status.monitoring:
    desc: "Show status of monitoring namespace"
    cmds:
      - kubectl get pods -n monitoring -o wide
      - kubectl get ingress -n monitoring